# Site settings
title: Olivia Cheng
description: I make things for humans
author: heyitsolivia

url: "https://heyitsolivia.github.io"
baseurl:

collections:
  work:
    output: true
    permalink: /working/on/:path/
  writing:
    output: true
    permalink: /writing/about/:path/

sass:
    sass_dir: assets/_sass

host: 0.0.0.0
